trigger: none

schedules:
- cron: "30 9 * * 1-5"   # 9:30 AM (market open time India)
  displayName: NSE Daily Run
  branches:
    include:
    - main
  always: true

pool:
  name: stock-pool
  #vmImage: 'ubuntu-latest'

steps:

- script: |
    python --version
  displayName: Check Python
  
- script: |
    pip install yfinance pandas ta requests
  displayName: Install Dependencies

- script: |
    python nse_strategy.py
  displayName: Run NSE Strategy

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'output'
    artifactName: 'NSE-Reports'